const ENDPOINT='__APPS_SCRIPT_WEB_APP_URL__';
const envelope=document.querySelector('#envelope'),intro=document.querySelector('#intro'),content=document.querySelector('#content'),musicBtn=document.querySelector('#music');
let audioCtx,notesTimer,isPlaying=false;
function playNote(freq,when,duration=.85){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,when);g.gain.linearRampToValueAtTime(.035,when+.08);g.gain.exponentialRampToValueAtTime(.001,when+duration);o.connect(g).connect(audioCtx.destination);o.start(when);o.stop(when+duration)}
function musicLoop(){if(!isPlaying)return;const now=audioCtx.currentTime;[261.63,329.63,392,523.25,440,349.23,392,329.63].forEach((n,i)=>playNote(n,now+i*.55));notesTimer=setTimeout(musicLoop,4400)}
function startMusic(){audioCtx ||= new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();isPlaying=true;musicBtn.classList.add('playing');musicLoop()}
function stopMusic(){isPlaying=false;clearTimeout(notesTimer);musicBtn.classList.remove('playing')}
envelope.addEventListener('click',()=>{envelope.classList.add('is-open');startMusic();setTimeout(()=>{intro.classList.add('open');content.classList.add('visible');content.removeAttribute('aria-hidden');document.body.classList.remove('locked');musicBtn.classList.add('show')},1350)},{once:true});
musicBtn.addEventListener('click',()=>isPlaying?stopMusic():startMusic());
const wedding=new Date('2026-11-08T13:00:00+02:00');function tick(){let d=Math.max(0,wedding-Date.now());const vals=[Math.floor(d/864e5),Math.floor(d/36e5)%24,Math.floor(d/6e4)%60,Math.floor(d/1e3)%60];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id).textContent=String(vals[i]).padStart(2,'0'))}tick();setInterval(tick,1000);
document.querySelector('#calendar').addEventListener('click',e=>{e.preventDefault();const body=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT','DTSTART:20261108T110000Z','DTEND:20261108T130000Z','SUMMARY:Γάμος Αχιλλέα & Γεωργίας','LOCATION:Ι.Ν. Αγίου Νικολάου, Λαγυνά','END:VEVENT','END:VCALENDAR'].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/calendar'}));a.download='achilleas-georgia.ics';a.click()});
const visitorId=localStorage.weddingVisitorId||crypto.randomUUID();localStorage.weddingVisitorId=visitorId;
async function send(payload){if(ENDPOINT.startsWith('__')){console.info('Demo mode',payload);return {ok:true}}const body=new URLSearchParams({...payload,visitorId,page:location.href,userAgent:navigator.userAgent});await fetch(ENDPOINT,{method:'POST',mode:'no-cors',body});return {ok:true}}
document.querySelector('#rsvpForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.target.querySelector('button'),status=document.querySelector('#formStatus');btn.disabled=true;status.textContent='Αποστολή…';try{await send({action:'rsvp',...Object.fromEntries(new FormData(e.target))});status.textContent='Ευχαριστούμε! Η απάντησή σας καταγράφηκε.';e.target.reset()}catch{status.textContent='Δεν έγινε η αποστολή. Δοκιμάστε ξανά.'}finally{btn.disabled=false}});
const details={IBAN:'Τα στοιχεία τραπεζικής κατάθεσης θα εμφανιστούν εδώ μόλις προστεθεί το IBAN.',IRIS:'Τα στοιχεία IRIS θα εμφανιστούν εδώ μόλις προστεθεί το κινητό ή ΑΦΜ.',ΟΧΙ:'Σας ευχαριστούμε θερμά — η παρουσία και οι ευχές σας είναι αρκετές!'};
document.querySelectorAll('[data-gift]').forEach(b=>b.addEventListener('click',async()=>{const choice=b.dataset.gift,box=document.querySelector('#giftDetail');document.querySelector('#giftDetailText').textContent=details[choice];box.hidden=false;box.scrollIntoView({behavior:'smooth',block:'center'});await send({action:'gift_click',gift:choice})}));document.querySelector('#closeGift').addEventListener('click',()=>document.querySelector('#giftDetail').hidden=true);
